let fase01 = [];

for (let i = 0; i < 17; i++) 
{
    fase01[i] = new Array(17);
};
for (let i = 0; i < 17; i++) 
{
    for(let j = 0; j < 17; j++)
    {
        switch (i) {
            case 1:
                fase01[i][0] = '*'
                fase01[i][1] = ' '
                fase01[i][2] = ' '
                fase01[i][3] = ' '
                fase01[i][4] = ' '
                fase01[i][5] = ' '
                fase01[i][6] = ' '
                fase01[i][7] = ' '
                fase01[i][8] = ' '
                fase01[i][9] = ' '
                fase01[i][10] = ' '
                fase01[i][11] = ' '
                fase01[i][12] = ' '
                fase01[i][13] = ' '
                fase01[i][14] = ' '
                fase01[i][15] = ' '
                fase01[i][16] = '*'
            break;
            case 2:
                fase01[i][0] = '*'
                fase01[i][1] = ' '
                fase01[i][2] = '&'
                fase01[i][3] = ' '
                fase01[i][4] = ' '
                fase01[i][5] = ' '
                fase01[i][6] = ' '
                fase01[i][7] = ' '
                fase01[i][8] = ' '
                fase01[i][9] = ' '
                fase01[i][10] = ' '
                fase01[i][11] = ' '
                fase01[i][12] = ' '
                fase01[i][13] = ' '
                fase01[i][14] = ' '
                fase01[i][15] = ' '
                fase01[i][16] = 'D'
            break;
            case 3:
                fase01[i][0] = '*'
                fase01[i][1] = ' '
                fase01[i][2] = ' '
                fase01[i][3] = ' '
                fase01[i][4] = ' '
                fase01[i][5] = ' '
                fase01[i][6] = ' '
                fase01[i][7] = ' '
                fase01[i][8] = ' '
                fase01[i][9] = ' '
                fase01[i][10] = ' '
                fase01[i][11] = ' '
                fase01[i][12] = ' '
                fase01[i][13] = ' '
                fase01[i][14] = ' '
                fase01[i][15] = ' '
                fase01[i][16] = '*'
            break;
            case 4:
                fase01[i][0] = '*'
                fase01[i][1] = '*'
                fase01[i][2] = '*'
                fase01[i][3] = '*'
                fase01[i][4] = '*'
                fase01[i][5] = '*'
                fase01[i][6] = '*'
                fase01[i][7] = '*'
                fase01[i][8] = '*'
                fase01[i][9] = '*'
                fase01[i][10] = '*'
                fase01[i][11] = ' '
                fase01[i][12] = ' '
                fase01[i][13] = ' '
                fase01[i][14] = ' '
                fase01[i][15] = ' '
                fase01[i][16] = '*'
            break;
            case 5:
                fase01[i][0] = '*'
                fase01[i][1] = ' '
                fase01[i][2] = ' '
                fase01[i][3] = ' '
                fase01[i][4] = ' '
                fase01[i][5] = ' '
                fase01[i][6] = ' '
                fase01[i][7] = ' '
                fase01[i][8] = ' '
                fase01[i][9] = ' '
                fase01[i][10] = ' '
                fase01[i][11] = ' '
                fase01[i][12] = ' '
                fase01[i][13] = ' '
                fase01[i][14] = ' '
                fase01[i][15] = ' '
                fase01[i][16] = '*'
            break;
            case 6:
                fase01[i][0] = '*'
                fase01[i][1] = ' '
                fase01[i][2] = ' '
                fase01[i][3] = ' '
                fase01[i][4] = ' '
                fase01[i][5] = ' '
                fase01[i][6] = ' '
                fase01[i][7] = ' '
                fase01[i][8] = ' '
                fase01[i][9] = ' '
                fase01[i][10] = ' '
                fase01[i][11] = ' '
                fase01[i][12] = ' '
                fase01[i][13] = ' '
                fase01[i][14] = ' '
                fase01[i][15] = ' '
                fase01[i][16] = '*'
            break;
            case 7:
                fase01[i][0] = '*'
                fase01[i][1] = ' '
                fase01[i][2] = ' '
                fase01[i][3] = ' '
                fase01[i][4] = ' '
                fase01[i][5] = ' '
                fase01[i][6] = ' '
                fase01[i][7] = ' '
                fase01[i][8] = ' '
                fase01[i][9] = ' '
                fase01[i][10] = ' '
                fase01[i][11] = ' '
                fase01[i][12] = ' '
                fase01[i][13] = ' '
                fase01[i][14] = ' '
                fase01[i][15] = ' '
                fase01[i][16] = '*'
            break;
            case 8:
                fase01[i][0] = '*'
                fase01[i][1] = ' '
                fase01[i][2] = ' '
                fase01[i][3] = ' '
                fase01[i][4] = ' '
                fase01[i][5] = ' '
                fase01[i][6] = '*'
                fase01[i][7] = '*'
                fase01[i][8] = '*'
                fase01[i][9] = '*'
                fase01[i][10] = '*'
                fase01[i][11] = '*'
                fase01[i][12] = '*'
                fase01[i][13] = '*'
                fase01[i][14] = '*'
                fase01[i][15] = '*'
                fase01[i][16] = '*'
            break;
            case 9:
                fase01[i][0] = '*'
                fase01[i][1] = ' '
                fase01[i][2] = ' '
                fase01[i][3] = ' '
                fase01[i][4] = ' '
                fase01[i][5] = ' '
                fase01[i][6] = ' '
                fase01[i][7] = ' '
                fase01[i][8] = ' '
                fase01[i][9] = ' '
                fase01[i][10] = ' '
                fase01[i][11] = ' '
                fase01[i][12] = ' '
                fase01[i][13] = 
                fase01[i][14] = 
                fase01[i][15] = 
                fase01[i][16] = '*'
            break;
            case 10:
                fase01[i][0] = '*'
                fase01[i][1] = ' '
                fase01[i][2] = ' '
                fase01[i][3] = ' '
                fase01[i][4] = ' '
                fase01[i][5] = ' '
                fase01[i][6] = ' '
                fase01[i][7] = ' '
                fase01[i][8] = ' '
                fase01[i][9] = ' '
                fase01[i][10] = ' '
                fase01[i][11] = ' '
                fase01[i][12] = ' '
                fase01[i][13] = ' '
                fase01[i][14] = ' '
                fase01[i][15] = ' '
                fase01[i][16] = '*'
            break;
            case 11:
                fase01[i][0] = '*'
                fase01[i][1] = ' '
                fase01[i][2] = ' '
                fase01[i][3] = ' '
                fase01[i][4] = ' '
                fase01[i][5] = ' '
                fase01[i][6] = ' '
                fase01[i][7] = ' '
                fase01[i][8] = ' '
                fase01[i][9] = ' '
                fase01[i][10] = ' '
                fase01[i][11] = ' '
                fase01[i][12] = ' '
                fase01[i][13] = ' '
                fase01[i][14] = ' '
                fase01[i][15] = ' '
                fase01[i][16] = '*'
            break;
            case 12:
                fase01[i][0] = '*'
                fase01[i][1] = '*'
                fase01[i][2] = '*'
                fase01[i][3] = '*'
                fase01[i][4] = '*'
                fase01[i][5] = '*'
                fase01[i][6] = '*'
                fase01[i][7] = '*'
                fase01[i][8] = '*'
                fase01[i][9] = '*'
                fase01[i][10] = '*'
                fase01[i][11] = ' '
                fase01[i][12] = ' '
                fase01[i][13] = ' '
                fase01[i][14] = ' '
                fase01[i][15] = ' '
                fase01[i][16] = '*'
            break;
            case 13:
                fase01[i][0] = '*'
                fase01[i][1] = ' '
                fase01[i][2] = ' '
                fase01[i][3] = ' '
                fase01[i][4] = '*'
                fase01[i][5] = ' '
                fase01[i][6] = ' '
                fase01[i][7] = ' '
                fase01[i][8] = ' '
                fase01[i][9] = ' '
                fase01[i][10] = '*'
                fase01[i][11] = ' '
                fase01[i][12] = ' '
                fase01[i][13] = ' '
                fase01[i][14] = ' '
                fase01[i][15] = ' '
                fase01[i][16] = '*'
            break;
            case 14:
                fase01[i][0] = '*'
                fase01[i][1] = ' '
                fase01[i][2] = 'o'
                fase01[i][3] = ' '
                fase01[i][4] = '*'
                fase01[i][5] = ' '
                fase01[i][6] = ' '
                fase01[i][7] = '*'
                fase01[i][8] = ' '
                fase01[i][9] = ' '
                fase01[i][10] = '*'
                fase01[i][11] = ' '
                fase01[i][12] = ' '
                fase01[i][13] = ' '
                fase01[i][14] = ' '
                fase01[i][15] = ' '
                fase01[i][16] = '*'
            break;
            case 15:
                fase01[i][0] = '*'
                fase01[i][1] = ' '
                fase01[i][2] = ' '
                fase01[i][3] = ' '
                fase01[i][4] = ' '
                fase01[i][5] = ' '
                fase01[i][6] = ' '
                fase01[i][7] = '*'
                fase01[i][8] = ' '
                fase01[i][9] = ' '
                fase01[i][10] = ' '
                fase01[i][11] = ' '
                fase01[i][12] = ' '
                fase01[i][13] = ' '
                fase01[i][14] = ' '
                fase01[i][15] = ' '
                fase01[i][16] = '*'
            break;
            default: fase01[i][j] = "*"
            break;
        }
    }
};

console.log(fase01);